### ISSUE TITLE
Compose functional Chainweb requests

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/kadena#144]
ℹ️ This issue is part of Epic #57

## Objective
- Implement a module to perform requests to Chainweb.

## Checklist
- [x] Initialization function `new/2` receiving the **HTTP method** and the **type of Chainweb API** (`pact`, `p2p`)
- [x] Functions to set **chain id** and **network**
- [x] Functions to add **body** and **headers** to the request.
- [x] Function `perform/1` to make the HTTP request once configured.
- [x] `results/2` to represent the API response as a defined structure.

**Comment by miguelnietoa** [comment]
Hi, I'll be working on this!
