### ISSUE TITLE
Block Payload endpoints implementation

### ISSUE THREAD

**Issue by L-Zuluaga** [kommitters/kadena#204]
ℹ️ This issue is an Epic 🎯

## Context
Implement the Block Payload endpoints logic.

## Checklist
- [x] #226
- [x] #227 
- [x] #228 
- [x] #229

**Comment by L-Zuluaga** [comment]
@einerzg @miguelnietoa @CristhianRodriguezMolina 
Hello guys, I wanted to discuss with you what do you think about this approach for organizing the issues and the epics using milestones on the projects in general on the MET? -> https://github.com/kommitters/kadena.ex/milestone/1? 
If it makes more sense, we could use epic issues to group the tasks on the checklists, if we want to separate even more the tasks. I already discussed this with Juan and he thought it would be valuable to discuss this with you and think about whether it is interesting to implement this approach.

**Comment by miguelnietoa** [comment]
I agree that we can use the milestones! Let's see how it works 👌🏻

**Comment by einerzg** [comment]
LGTM 👍🏽
