### ISSUE TITLE
Config endpoint implementation

### ISSUE THREAD

**Issue by L-Zuluaga** [kommitters/kadena#207]
## Checklist
- [ ] [Configuration of Chainweb Node ](https://api.chainweb.com/openapi/#tag/config)

**Comment by L-Zuluaga** [comment]
@miguelnietoa @EdwinGuayacan this one only requires to implement 1 endpoint, for this specific case we could use a simple issue instead of an epic with the issue linked to it, do you agree?

**Comment by Odraxs** [comment]
This issue was not implemented because we discovered that the API returns a `404` status after making requests with Postman.
