### ISSUE TITLE
Get Batch of Block Payload With Outputs

### ISSUE THREAD

**Issue by L-Zuluaga** [kommitters/kadena#229]
ℹ️ This issue is part of Epic #204

## Objective
Implement the POST request: [Get Batch of Block Payload With Outputs](https://api.chainweb.com/openapi/#tag/payload/paths/~1chain~1%7Bchain%7D~1payload~1outputs~1batch/post)

**Comment by EdwinGuayacan** [comment]
This issue was not implemented because after making requests with Postman, we noticed that the API rejects the connection and returns a 404 status.
